<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xabbo.Common" Version="1.0.4" />
    <PackageReference Include="Xabbo.GEarth" Version="1.0.1" />
    <PackageReference Include="Xabbo.Messages" Version="1.0.2" />
  </ItemGroup>

</Project>